version: '3.9'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elastic
    env_file:
      - ./kibana.env
    networks:
      - elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - ./elastic.env
    networks:
      - elastic

networks:
  elastic:
    driver: bridge