filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/monitor/out.log
filebeat.modules:
- module: nginx
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana.host: "http://kibana:5601"
output.elasticsearch:
  hosts: ["elastic:9200"]
  protocol: "http"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

